REVOKE evalpam_birder, evalpam_admin FROM {`DB_EVALPAM_USER`};
-- REVOKE SELECT ON public.app_users FROM evalpam_user;
DROP USER IF EXISTS {`DB_EVALPAM_USER`};
DROP ROLE IF EXISTS evalpam_birder;
DROP ROLE IF EXISTS evalpam_admin;
CREATE ROLE evalpam_birder;
CREATE ROLE evalpam_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO evalpam_birder;

ALTER DEFAULT PRIVILEGES IN SCHEMA import
GRANT SELECT, INSERT ON TABLES TO evalpam_birder;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO evalpam_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA import
GRANT ALL PRIVILEGES ON TABLES TO evalpam_admin;
