
-- Table: public.lut_species_code

-- DROP TABLE IF EXISTS public.lut_species_code;

CREATE TABLE IF NOT EXISTS public.lut_species_code
(
    species_id smallint GENERATED BY DEFAULT AS IDENTITY,
    species_short character varying(10) COLLATE pg_catalog."default" NOT NULL,
    species_long_de character varying(99) COLLATE pg_catalog."default" NOT NULL,
    species_long_en character varying(99) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expired_at timestamptz,
    CONSTRAINT lut_species_code_pkey PRIMARY KEY (species_id)
);

-- Table: public.lut_behavior_code

-- DROP TABLE IF EXISTS public.lut_behavior_code;

CREATE TABLE IF NOT EXISTS public.lut_behavior_code
(
    behavior_id smallint GENERATED BY DEFAULT AS IDENTITY,
    behavior_short character varying(10) COLLATE pg_catalog."default",
    behavior_long_de character varying(99) COLLATE pg_catalog."default",
    behavior_long_en character varying(99) COLLATE pg_catalog."default",
    created_at timestamptz NOT NULL DEFAULT now(),
    expired_at timestamptz,
    CONSTRAINT lut_behavior_code_pkey PRIMARY KEY (behavior_id)
);


CREATE TABLE IF NOT EXISTS public.lut_annotation_type_code
(
    annotation_type_id smallint GENERATED BY DEFAULT AS IDENTITY,
    annotation_type_short character varying(10) COLLATE pg_catalog."default",
    annotation_type_long_de character varying(99) COLLATE pg_catalog."default",
    annotation_type_long_en character varying(99) COLLATE pg_catalog."default",
    created_at timestamptz NOT NULL DEFAULT now(),
    expired_at timestamptz,
    CONSTRAINT lut_annotation_type_code_pkey PRIMARY KEY (annotation_type_id)
);


