-- Migration: add lut_abiotic_sound_code lookup table and seed data
-- Safe to re-run (IF NOT EXISTS / ON CONFLICT DO NOTHING guards).

CREATE TABLE IF NOT EXISTS public.lut_abiotic_sound_code
(
    abiotic_sound_id smallint GENERATED BY DEFAULT AS IDENTITY,
    abiotic_sound_short character varying(20) COLLATE pg_catalog."default" NOT NULL,
    abiotic_sound_long_de character varying(99) COLLATE pg_catalog."default" NOT NULL,
    abiotic_sound_long_en character varying(99) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expired_at timestamptz,
    CONSTRAINT lut_abiotic_sound_code_pkey PRIMARY KEY (abiotic_sound_id),
    CONSTRAINT uq_abiotic_sound_short UNIQUE (abiotic_sound_short)
);

INSERT INTO public.lut_abiotic_sound_code
    (abiotic_sound_short, abiotic_sound_long_de, abiotic_sound_long_en)
VALUES
    ('TRANSPORT',   'Verkehr (Straße, Schiene)',      'Road / rail traffic'),
    ('AIRCRAFT',    'Luftfahrzeug',                   'Aircraft'),
    ('WIND',        'Wind',                           'Wind'),
    ('THUNDER',     'Donner',                         'Thunder'),
    ('RAIN',        'Regen',                          'Rain'),
    ('BRANCHES',    'Bewegte Äste / Laub',            'Moving branches / foliage'),
    ('WATER',       'Fließendes Wasser',              'Running water'),
    ('MACHINERY',   'Maschinen / technische Geräte',  'Machinery / technical equipment'),
    ('HUMAN',       'Menschliche Stimme / Aktivität', 'Human voice / activity'),
    ('ANIMAL_DOM',  'Haustiere (Hund, Kuh u.ä.)',     'Domestic animals (dog, cow, etc.)'),
    ('INSECTS',     'Insekten',                       'Insects'),
    ('UNSPECIFIED', 'Unspezifisch',                   'Unspecified'),
    ('OTHER',       'Sonstiges',                      'Other')
ON CONFLICT DO NOTHING;
